---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      export PATH=/opt/IBM/node-v4.2/bin:$PATH

      npm install
      npm run build

      tar -czf node_modules.tar.gz node_modules
      rm -rf node_modules
- name: Deploy to Test
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 'Test Job'
    type: tester
    script: |-
      #!/bin/bash
      # Supposed to be testing through e.g. Saucelabs, but not configured and therefore disabled.
      # Must be configured as module in Toolchain, and selected.
  - name: Deploy Test
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_TEST_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -b https://github.com/cloudfoundry-community/staticfile-buildpack.git
- name: Deploy to Production
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  jobs:
  - name: Deploy Prod
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}" -b https://github.com/cloudfoundry-community/staticfile-buildpack.git
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
